version: "3.7"

services:
  frontend:
    container_name: frontend
    build: "./frontend"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    ports:
      - "3000:3000"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
  backend:
    build: "./backend"
    volumes:
      - /app/node_modules
      - ./server:/app
  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: my-secret-pw
  #   ports:
  #     - "3306:3306"
