version: "3.7"

services:
  frontend:
    container_name: frontend
    build: "./frontend"
    volumes:
      - "/home/node/node_modules"
      - "./frontend:/home/node"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build: "./backend"
    volumes:
      - "/home/node/node_modules"
      - "./backend:/home/node"
    ports:
      - "3001:3001"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "instagram"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
